// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Directive: accountMenu', function() {
    var scope;
    beforeEach(module('ngApp'));
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      return scope = $rootScope.$new();
    }));
    return it('should make hidden element visible', inject(function($compile) {
      var element;
      element = angular.element('<account-menu></account-menu>');
      element = $compile(element)(scope);
      return expect(element.text()).toBe('this is the accountMenu directive');
    }));
  });

}).call(this);

/*
//@ sourceMappingURL=account-menu.map
*/
