// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: AppCreatorCtrl', function() {
    var AppCreatorCtrl, scope;
    beforeEach(module('ngApp'));
    AppCreatorCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return AppCreatorCtrl = $controller('AppCreatorCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.awesomeThings.length).toBe(3);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=app-creator.map
*/
