// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('ngApkreator').controller('FeaturesCtrl', function($scope, $rootScope) {
    return $rootScope.headerMenuItems = [
      {
        name: "Home",
        url: "#/",
        "class": ""
      }, {
        name: "App Creator",
        url: "#/app-creator",
        "class": ""
      }, {
        name: "Features",
        url: "#/features",
        "class": "active"
      }, {
        name: "Contact",
        url: "#",
        "class": ""
      }
    ];
  });

}).call(this);

/*
//@ sourceMappingURL=features.map
*/
